#pragma config(Sensor, in1,    Line,           sensorLineFollower)
#pragma config(Motor,  port2,           InitGate,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           ColorGate,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           DirectionGate, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void intake()
{
setServo(InitGate, -30);
setServo(InitGate, 20);
wait(.05);
setServo(InitGate, -30);
wait(.06);
}
task checkmarble
{
if (SensorValue(Line)>900 && SensorValue(Line)<1300){ // Steel Marble
	setServo(DirectionGate, 10);
}
if (SensorValue(Line)>400 && SensorValue(Line)<700){ // Plastic Marble
	setServo(DirectionGate, -55);
}
if (SensorValue(Line)>0 && SensorValue(Line)<400){ // Wood Marble
	setServo(DirectionGate, 100);
}
if (SensorValue(Line)>0 && SensorValue(Line)<0){ // Wood Marble
	setServo(DirectionGate, x);
}
}


task main()
{
setServo(InitGate, -30);
setServo(ColorGate, 0);
intake();
wait(1.5);
setServo(ColorGate, -15);
startTask(checkmarble);
wait(4);
setServo(ColorGate, 20);
wait(2);




}
